const VACCINE_TYPES = {
  SPUTNIK: 'SPUTNIK',
  ASTRAZENECA: 'ASTRAZENECA',
  PFIZER: 'PFIZER',
  JHONSON: 'JHONSON',
};
const VACCINATION_STATUS = {
  VACCINATED: 'VACCINATED',
  NO_VACCINATED: 'NO_VACCINATED',
};

module.exports = {
  VACCINATION_STATUS,
  VACCINE_TYPES,
}